### ISSUE TITLE
Composer.json points at wrong version of php-domain-parser.

### ISSUE THREAD

**Issue by yo-l1982** [jwage/purl#26]
Hello,

I had to change the composer.json.

```
    "require": {
        "php": ">=5.3.0",
        "jeremykendall/php-domain-parser": "1.*"
    } 
```

to

```
    "require": {
        "php": ">=5.3.0",
        "jeremykendall/php-domain-parser": "1.1.0"
    } 
```

To install this.
Version 1.2.0 does not seem to be compatible and the wildcard auto points at that one.

**Comment by phrazer** [comment]
php-domain-parser is now at 4.0 version, could we upgrade to latest? best,
