### ISSUE TITLE
Why is the canonical domain reversed?

### ISSUE THREAD

**Issue by CMCDragonkai** [jwage/purl#27]
This is apparently the canonical domain:

```
com.jwage.domain.sub/index.php?param1=value1
```

Also I noticed that the README doesn't mention that it also includes the query parameters. It's a bit confusing since it was part of the Domains section.

Would be good to note the new $resource parameter too!

**Comment by fahmilatib** [comment]
ping @jwage

**Comment by jwage** [comment]
I can't remember the reasoning. When I was writing this library, I researched other similar libraries from ruby, python, etc. and I saw it here https://github.com/pauldix/domainatrix

@jeremykendall do you remember the reasoning by chance?

**Comment by jeremykendall** [comment]
I don’t remember either. I’m not sure there is a good reason besides sorting, but it’s been a while since I’ve worked with these libs.
