### ISSUE TITLE
Problem with parsing a URL contains # before the query string

### ISSUE THREAD

**Issue by hossam-fares** [jwage/purl#28]
I have this Url 'http://www.myurl.com/#!/any_path/?param1=val1' and I want to add a new query parameter to it, so I did that:

```
        $url = new \Purl\Url('http://www.myurl.com/#!/any_path/?param1=val1');
        $url->getQuery()->set('param2', 'val2');
        echo $url->getUrl(); //http://www.myurl.com/?param2=val2#!/any_path/?param1=val1
```

I'm expecting this url 'http://www.myurl.com/#!/any_path/?param1=val1&param2=val2' as an output not 'http://www.myurl.com/?param2=val2#!/any_path/?param1=val1'

Any Idea!

**Comment by jwage** [comment]
As @mrclay mentioned this is working as expected.
