### ISSUE TITLE
Feature request: building relative urls

### ISSUE THREAD

**Issue by AidasK** [jwage/purl#36]
Library should be able to create relative urls:

``` php
$url = new \Purl\Url('/events');
$url->query->set('param1', 'value1');
echo $url->getUrl();
```

Expected output should be:

```
/events?param1=value1
```

**Comment by phrazer** [comment]
+1 for this also

**Comment by jwage** [comment]
:+1: Anyone willing to implement this?

**Comment by itstudiocz** [comment]
Can #52 be merged into master?

**Comment by kzap** [comment]
@jwage can we merge this?

**Comment by jszobody** [comment]
@jwage Any update on this? 

I needed to do relative URL manipulation, came across this package, now just waiting for the PR merge.

**Comment by jwage** [comment]
@jszobody I don't think anyone has stood up to implement this yet. Let me know if you are interested in working on it. Thanks, Jon

**Comment by jwage** [comment]
Sorry nevermind, I missed PR #52. Looking at it now.

**Comment by peter279k** [comment]
This issue has been fixed and it can be closed.
