### ISSUE TITLE
Feature request: resolving urls

### ISSUE THREAD

**Issue by pekhota** [jwage/purl#39]
It will be very cool to have something like this: http://nodejs.org/api/url.html#url_url_resolve_from_to

$url->resolve('/one/two/three', 'four')         // '/one/two/four'
$url->resolve('http://example.com/', '/one')    // 'http://example.com/one'
$url->resolve('http://example.com/one', '/two') // 'http://example.com/two'

**Comment by jwage** [comment]
This is easily possible with this:

```
$url = new Url('https://jwage.com/kubota-l210/');
$url->path = '/about';
```

Are you just wanting another way to do it? or?
