### ISSUE TITLE
How to remove a part of the url ?

### ISSUE THREAD

**Issue by mseshachalam** [jwage/purl#43]
to remove `host` from the url

```
$url->set('host', null) or $url->remove('host')
```

if i do $url->set('host', null) and $url->getUrl() gives me something like ://google.com. The "http" alone is gone. 
and if set the host to 'http' to //google.com url, it gives http://://google.com

**Comment by peter279k** [comment]
Consider the sample code:

```
$url = new Url('https://google.com');
$url->remove('host', null);
echo $url->getUrl();
```
It will return the ```/``` now and it happens on this [line](https://github.com/jwage/purl/blob/master/src/Purl/Url.php#L400).

And consider another code:

```
$url = new Url('https://google.com');
$url->set('host', '//google.com');
echo $url->getUrl();
```
It will return the ```https:////google.com/``` value.
If you want to get the ```https://google.com```, you can use the following code:

```
$url = new Url('https://google.com');
$url->set('host', 'google.com');
echo $url->getUrl();
```
The ```//google.com``` has included the ```//``` protocol, and the host only includes the ```google.com```.
Then it will return the ```https://google.com/``` value.
@jwage, I don't know whether this issue has been fixed.
I think that issue has already been fixed.
