### ISSUE TITLE
how to set IP address as host in a url ?

### ISSUE THREAD

**Issue by mseshachalam** [jwage/purl#44]
if i try to set an IP address as host name it give an InvalidArgument exception. 

```
$url = 'http://www.google.com';
$url = new Url($url);
$url->set('host', '8.8.8.8');
```

now $url->getUrl() results in InvalidArgumentException

**Comment by peter279k** [comment]
This issue has already been fixed.
You should use the latest version ```0.08```.
Here is my sample code:
```
$url = new Url('https://google.com');
$url->set('host', '8.8.8.8');
echo $url->getUrl(); // https://8.8.8.8/
```

Thanks.
