### ISSUE TITLE
Incompatible with modern software

### ISSUE THREAD

**Issue by Stratadox** [jwage/purl#61]
Any software package with a dev dependency on PhpUnit 7+ is incompatible with `jwage/purl`:

```
jwage/purl dev-master requires phpunit/phpunit ^4.8|^5.5|^6.5
```
Conflicts with:
```
Installation request for phpunit/phpunit ~7.0
```

The problem is probably caused by phpunit being in `require ` rather than `require -dev`.

**Comment by jwage** [comment]
@peter279k could you look at this by chance?

**Comment by peter279k** [comment]
It seems that the package dependency problem.
@jwage. How about setting the ```jwage/purl dev-master requires phpunit/phpunit ^4.8|^5.5|^6.5|^7.0``` in ```composer.json```?

**Comment by jwage** [comment]
Fixed in https://github.com/jwage/purl/releases/tag/v0.0.9
