### ISSUE TITLE
Why does remove() return "void"

### ISSUE THREAD

**Issue by holtkamp** [jwage/purl#74]
Personally I am not a big fan of fluent interfaces, but I _do_ think that in case one uses them, it should be done in a consistent way. 

Is there any particular reason that `remove()` (which is specific to this library) returns `void` ?

https://github.com/jwage/purl/blob/beb717588f9a9d24abd62d676ab5014d25edefc5/src/Purl/AbstractPart.php#L89

When this is possible:

```php
$url = \Purl\Url::parse('http://jwage.com')
    ->set('scheme', 'https')
    ->set('host', 'jwageMirror.com');
```

Then this _should_ (?) also be possible?:

```php
$url = \Purl\Url::parse('http://jwage.com')
    ->remove('scheme')
    ->remove('host');
```

**Comment by jwage** [comment]
No particular reason that I can remember. Probably just an oversight. We can change this if you would like.
