### ISSUE TITLE
require old jeremykendall/php-domain-parser version

### ISSUE THREAD

**Issue by Smartsasse** [jwage/purl#75]
I'm getting the following errors. This is because jwage/purl requires jeremykendall/php-domain-parser "^1.3.1". Could you change to allow a newer version please.

PHP Deprecated:  idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /var/www/vhosts/rubus.pineberry.com/vendor/jeremykendall/php-domain-parser/library/Pdp/Parser.php on line 209

PHP Deprecated:  idn_to_utf8(): INTL_IDNA_VARIANT_2003 is deprecated in /var/www/vhosts/rubus.pineberry.com/vendor/jeremykendall/php-domain-parser/library/Pdp/Parser.php on line 192

**Comment by jwage** [comment]
@jeremykendall thoughts?

**Comment by jeremykendall** [comment]
@nyamsprod has been doing all of the recent dev and maintenance on the library. Can you chime in and propose a solution, @nyamsprod?

**Comment by nyamsprod** [comment]
@Smartsasse @jwage Unfortunately, Purl still uses v1 or Pdp while Pdp has moved to version 5 :cry: With many BC breaks like **removing the URL parser**. So I don't know exactly how to resolve this issue since it has been resolved in v5 (and was one the reason to move to v5 in the first place)

**Comment by jwage** [comment]
I think jwage/purl just needs to upgrade jeremykendall/php-domain-parser
